POST http://localhost:3000/campaigns

{
    "name": "jefferson33",
    "content": "change password3",
    "emails": ["teste33@email.com"]
}

###

GET http://localhost:3000/campaigns/d6tdkvf0e3a58v2v3beg

###

PATCH http://localhost:3000/campaigns/d6lj0sf0e3a0n22fm50g/cancel

###
DELETE http://localhost:3000/campaigns/d6tdkvf0e3a58v2v3beg
